<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../src/Runax.Messaging/Runax.Messaging.csproj" />
    <ProjectReference Include="../../src/Runax.Messaging.Transports.Google.PubSub/Runax.Messaging.Transports.Google.PubSub.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Cloud.PubSub.V1" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
  </ItemGroup>
</Project>
