<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../src/Runax.Messaging/Runax.Messaging.csproj" />
    <ProjectReference Include="../../src/Runax.Messaging.Transports.Aws.Sns/Runax.Messaging.Transports.Aws.Sns.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.SimpleNotificationService" />
    <PackageReference Include="AWSSDK.SQS" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
  </ItemGroup>
</Project>
