<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Azure Event Hubs transport for Runax.Messaging.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Runax.Messaging.Abstractions/Runax.Messaging.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Messaging.EventHubs" />
    <PackageReference Include="Azure.Messaging.EventHubs.Processor" />
    <PackageReference Include="Azure.Storage.Blobs" />
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Runax.Messaging.Transports.Azure.EventHubs.Tests" />
  </ItemGroup>
</Project>
