<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../src/Runax.Messaging/Runax.Messaging.csproj" />
    <ProjectReference Include="../../src/Runax.Messaging.Transports.Azure.EventHubs/Runax.Messaging.Transports.Azure.EventHubs.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Messaging.EventHubs" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
  </ItemGroup>
</Project>
